# Generated by Django 3.2.4 on 2022-03-01 12:47

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content2', ckeditor_uploader.fields.RichTextUploadingField()),
                ('about_image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get In Touch', max_length=1000)),
                ('description', models.TextField(default='Not to give you mom-guilt or anything, but it would be so nice to hear from you every once in a while.', max_length=1000)),
                ('phone', models.CharField(default='+1 (289) 788-9196', max_length=30)),
                ('email', models.EmailField(blank=True, default='office@cyberkoch.com', max_length=254)),
                ('sales', models.EmailField(blank=True, default='sales@cyberkoch.com', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='CategoryCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Category_Course',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('full_name', models.CharField(blank=True, max_length=120, null=True)),
                ('position', models.CharField(blank=True, max_length=120, null=True)),
                ('user_image', models.ImageField(upload_to='media')),
                ('comment_count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=120)),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', ckeditor_uploader.fields.RichTextUploadingField()),
                ('course_count', models.IntegerField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('duration', models.CharField(max_length=100)),
                ('teachers_count', models.IntegerField()),
                ('max_students', models.IntegerField()),
                ('skill_level', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='course_img')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coruse_category', to='core.categorycourse')),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('course_number', models.CharField(max_length=100)),
                ('course_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('queastion', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Curriculum',
            },
        ),
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Faq_Question',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logos', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Main',
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Why CyberKoch Academy?',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('experience', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JS'), ('JAVA', 'JAVA'), ('DJANGO', 'DJANGO'), ('PYTHON', 'PYTHON'), ('C', 'C'), ('C#', 'C#')], max_length=100)),
                ('highest_education', models.CharField(choices=[('No Degree', 'No Degree'), ('High School Diploma', 'High School Diploma'), ('Bachelor’s Degree', 'Bachelor’s Degree'), ('Master’s Degree', 'Master’s Degree'), ('PHD', 'PHD')], max_length=100)),
                ('name_educational', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('work_schedule', models.CharField(choices=[('Employed Full Time', 'Employed Full Time'), ('Employed Part Time', 'Employed Part Time'), ('Not Employed', 'Not Employed')], max_length=100)),
                ('hear_about', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Register',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='core.about')),
                ('course_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_images', to='core.course')),
                ('curric_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curric_images', to='core.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', ckeditor_uploader.fields.RichTextUploadingField()),
                ('about_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_head', to='core.about')),
                ('curriculum_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_head', to='core.curriculum')),
                ('faq_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_head', to='core.faqquestion')),
            ],
        ),
        migrations.CreateModel(
            name='FaqAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=1000, null=True)),
                ('question_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='core.faqquestion')),
            ],
            options={
                'verbose_name_plural': 'Faq_Answer',
            },
        ),
        migrations.CreateModel(
            name='CurriculumDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, max_length=2000, null=True)),
                ('curriculum_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_detail', to='core.curriculum')),
            ],
            options={
                'verbose_name_plural': 'CurriculumDetail',
            },
        ),
    ]
